package com.example.salestracker;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 int NAVY=Color.rgb(13,43,78),TEAL=Color.rgb(0,166,132),BLUE=Color.rgb(37,116,226),PURPLE=Color.rgb(112,76,190),RED=Color.rgb(205,68,68),BG=Color.rgb(247,249,252),TEXT=Color.rgb(29,43,61),MUTED=Color.rgb(105,117,132),BORDER=Color.rgb(220,228,238); LinearLayout content;String page="home";SharedPreferences pref;ArrayList<Product> ps=new ArrayList<>();
 static class Product{String n;double p,c;Product(String n,double p,double c){this.n=n;this.p=p;this.c=c;}}
 int d(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);} LinearLayout.LayoutParams wt(int h,float w){return new LinearLayout.LayoutParams(0,h,w);}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;} GradientDrawable border(){GradientDrawable g=bg(Color.WHITE,12);g.setStroke(d(1),BORDER);return g;}
 TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;} TextView b(String s,float z,int c){TextView v=t(s,z,c);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 EditText e(String h,String s){EditText x=new EditText(this);x.setHint(h);x.setText(s);x.setTextSize(15);x.setTextColor(TEXT);x.setSingleLine(true);x.setPadding(d(12),0,d(12),0);x.setBackground(border());return x;} EditText se(String s){EditText x=e("",s);x.setTextSize(13);x.setGravity(Gravity.CENTER);x.setPadding(d(3),0,d(3),0);return x;}
 Button btn(String s,int c){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(14);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setAllCaps(false);x.setMinHeight(0);x.setMinWidth(0);x.setPadding(d(8),0,d(8),0);x.setBackground(bg(c,13));return x;}
 void add(View v){content.addView(v,lp(-1,-2));}void gap(int h){Space s=new Space(this);content.addView(s,lp(-1,d(h)));}void gapIn(LinearLayout l,int h){Space s=new Space(this);l.addView(s,lp(-1,d(h)));}
 @Override public void onCreate(Bundle x){super.onCreate(x);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);pref=getSharedPreferences("sales_tracker",0);load();home();}
 @Override public void onBackPressed(){if(!page.equals("home"))home();else super.onBackPressed();}
 void load(){ps.clear();String r=pref.getString("products","");if(r.length()==0){defaults();return;}for(String q:r.split("\\|")){String[] a=q.split("~",-1);if(a.length==3)try{ps.add(new Product(a[0],Double.parseDouble(a[1]),Double.parseDouble(a[2])));}catch(Exception z){}}if(ps.isEmpty()){pref.edit().remove("products").apply();defaults();}}
 void defaults(){ps.add(new Product("Korean 40gm Chain",31,2250));ps.add(new Product("4pcs",9,1728));ps.add(new Product("8pcs CP",8,1692));ps.add(new Product("14pcs",12,2120));ps.add(new Product("Low Fat",5,1020));ps.add(new Product("Ramen 5pcs",14,2400));ps.add(new Product("Nata",3,550));ps.add(new Product("Ice Lolly",5,989));ps.add(new Product("Jhal Boroi",6,1407));ps.add(new Product("Jelly",7,1350));}
 void save(){StringBuilder s=new StringBuilder();for(Product p:ps)s.append(p.n.replace("~"," ")).append("~").append(p.p).append("~").append(p.c).append("|");pref.edit().putString("products",s.toString()).apply();}
 double num(String s){try{return Double.parseDouble(s.replace(",","").replace("৳","").trim());}catch(Exception z){return 0;}}String f(double x){return Math.abs(x-Math.round(x))<.001?""+Math.round(x):String.format(Locale.US,"%.2f",x);}String money(double x){return"৳ "+String.format(Locale.US,"%,.0f",x);}double pct(){double x=0;for(Product p:ps)x+=p.p;return x;}long cart(double a,double c){return c>0?(long)Math.ceil(a/c):0;}
 void base(String title,String id){page=id;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(d(8),0,d(14),0);bar.setBackgroundColor(NAVY);root.addView(bar,lp(-1,d(56)));if(!id.equals("home")){TextView back=b("‹",32,Color.WHITE);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->home());bar.addView(back,lp(d(42),d(56)));}TextView titleV=b(title,20,Color.WHITE);titleV.setPadding(d(6),0,0,0);bar.addView(titleV,wt(d(56),1));ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(d(14),d(14),d(14),d(24));sc.addView(content,lp(-1,-2));root.addView(sc,lp(-1,0));((LinearLayout.LayoutParams)sc.getLayoutParams()).weight=1;setContentView(root);}
 LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setBackground(bg(Color.WHITE,18));x.setPadding(d(16),d(12),d(16),d(12));return x;}
 void home(){base("Sales Tracker","home");LinearLayout h=card();h.setOrientation(LinearLayout.VERTICAL);h.addView(b("Welcome Back!",25,NAVY),lp(-1,d(38)));h.addView(t("Plan smart. Sell better.",15,MUTED),lp(-1,d(28)));add(h);gap(12);homeCard("🎯","Sales Planning Maker","Set a target and create product-wise planning.",TEAL,v->planning());gap(10);homeCard("◔","Product Wise Sales","Enter sales → estimate → edit → final result.",BLUE,v->wise());gap(10);homeCard("⚙","Product Setup","Manage product name, sales % and carton price.",PURPLE,v->setup());gap(14);LinearLayout st=card();TextView a=b("Products\n"+ps.size(),14,TEXT);a.setGravity(Gravity.CENTER);st.addView(a,wt(d(56),1));TextView q=b("Total %\n"+f(pct())+"%",14,TEAL);q.setGravity(Gravity.CENTER);st.addView(q,wt(d(56),1));add(st);}
 void homeCard(String icon,String title,String sub,int color,View.OnClickListener click){LinearLayout x=card();x.setOrientation(LinearLayout.VERTICAL);x.setOnClickListener(click);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView i=t(icon,24,color);i.setGravity(Gravity.CENTER);h.addView(i,lp(d(42),d(42)));TextView z=b(title,19,color);z.setPadding(d(8),0,0,0);h.addView(z,wt(d(42),1));x.addView(h,lp(-1,d(44)));TextView s=t(sub,14,MUTED);s.setPadding(d(50),0,0,0);x.addView(s,lp(-1,d(30)));add(x);}
 void headers(LinearLayout x){LinearLayout h=new LinearLayout(this);h.addView(b("PRODUCT",11,NAVY),wt(d(34),1));h.addView(b("%",11,NAVY),lp(d(55),d(34)));h.addView(b("AMOUNT",11,NAVY),lp(d(92),d(34)));h.addView(b("CARTON",11,NAVY),lp(d(62),d(34)));x.addView(h,lp(-1,d(34)));}
 LinearLayout row(Product p,double amount,long c){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView name=t(p.n,13,TEXT);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(name,wt(d(50),1));r.addView(se(f(p.p)),lp(d(55),d(46)));r.addView(se(String.format(Locale.US,"%.0f",amount)),lp(d(92),d(46)));r.addView(se(""+c),lp(d(62),d(46)));return r;}
 void planning(){base("Sales Planning Maker","planning");add(b("Create your target plan",19,NAVY));gap(4);add(b("Total Target",14,TEXT));EditText target=e("Enter target amount","500000");add(target);gap(10);Button go=btn("Calculate Planning",TEAL);add(go);gap(12);LinearLayout table=card();table.setOrientation(LinearLayout.VERTICAL);add(table);Runnable render=()->{table.removeAllViews();headers(table);double total=num(target.getText().toString()),sum=0;long cs=0;for(Product p:ps){double a=total*p.p/100;long c=cart(a,p.c);table.addView(row(p,a,c),lp(-1,d(54)));sum+=a;cs+=c;}table.addView(b("TOTAL     "+f(pct())+"%     "+money(sum)+"     "+cs+" cartons",13,TEAL),lp(-1,d(42)));};go.setOnClickListener(v->{hide();render.run();});render.run();}
 void wise(){base("Product Wise Sales","wise");add(b("Estimate product-wise sales",19,NAVY));gap(4);add(b("Total Sales",14,TEXT));EditText sales=e("Enter total sales","15200");add(sales);gap(10);Button go=btn("Get Estimated Result",BLUE);add(go);gap(12);LinearLayout table=card();table.setOrientation(LinearLayout.VERTICAL);add(table);Runnable render=()->{table.removeAllViews();table.addView(b("Estimated values — edit % / amount / carton",13,NAVY),lp(-1,d(34)));headers(table);double total=num(sales.getText().toString());for(Product p:ps){double a=total*p.p/100;table.addView(row(p,a,cart(a,p.c)),lp(-1,d(54)));}gapIn(table,10);Button fin=btn("✓  Final Result",TEAL);table.addView(fin,lp(-1,d(50)));fin.setOnClickListener(v->{hide();finalPage(total,table);});};go.setOnClickListener(v->{hide();render.run();});render.run();}
 void finalPage(double input,LinearLayout old){base("Final Result","final");double pp=0,aa=0;long cc=0;ArrayList<String[]> data=new ArrayList<>();for(int i=2;i<old.getChildCount();i++){View v=old.getChildAt(i);if(!(v instanceof LinearLayout))continue;LinearLayout r=(LinearLayout)v;if(r.getChildCount()<4)continue;try{String name=((TextView)r.getChildAt(0)).getText().toString();double p=num(((EditText)r.getChildAt(1)).getText().toString()),a=num(((EditText)r.getChildAt(2)).getText().toString());long c=Math.round(num(((EditText)r.getChildAt(3)).getText().toString()));pp+=p;aa+=a;cc+=c;data.add(new String[]{name,f(p)+"%",money(a),""+c});}catch(Exception z){}}add(b("✓ Final Product-Wise Sales",21,TEAL));gap(8);LinearLayout sum=card();sum.setOrientation(LinearLayout.VERTICAL);summary(sum,"Input Sales",money(input));summary(sum,"Final Amount",money(aa));summary(sum,"Total Carton",""+cc);summary(sum,"Total Percentage",f(pp)+"%");add(sum);gap(12);LinearLayout out=card();out.setOrientation(LinearLayout.VERTICAL);LinearLayout h=new LinearLayout(this);cell(h,"PRODUCT",1,true);cell(h,"%",.55f,true);cell(h,"AMOUNT",1.1f,true);cell(h,"CARTON",.75f,true);out.addView(h,lp(-1,d(38)));for(String[] a:data){LinearLayout r=new LinearLayout(this);cell(r,a[0],1,false);cell(r,a[1],.55f,false);cell(r,a[2],1.1f,false);cell(r,a[3],.75f,false);out.addView(r,lp(-1,d(44)));}add(out);gap(14);Button home=btn("Back to Home",TEAL);add(home);home.setOnClickListener(v->home());}
 void summary(LinearLayout p,String a,String z){LinearLayout r=new LinearLayout(this);r.addView(t(a,14,MUTED),wt(d(34),1));TextView x=b(z,15,NAVY);x.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.addView(x,wt(d(34),1));p.addView(r,lp(-1,d(34)));}void cell(LinearLayout r,String s,float w,boolean strong){TextView v=strong?b(s,11,NAVY):t(s,11,TEXT);v.setSingleLine(true);v.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(v,wt(d(44),w));}
 void setup(){base("Product Setup","setup");add(b("Manage your products",19,NAVY));add(t("Name • Sales % • Carton price",14,MUTED));gap(10);Button add=btn("＋  Add Product",TEAL);this.add(add);gap(12);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);this.add(list);final Runnable[] refresh={null};Runnable render=()->{list.removeAllViews();for(int i=0;i<ps.size();i++){final int ix=i;Product p=ps.get(i);LinearLayout r=card();r.setGravity(Gravity.CENTER_VERTICAL);TextView name=b(p.n,14,NAVY);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(name,wt(d(54),1));TextView pctV=b(f(p.p)+"%",14,TEAL);pctV.setGravity(Gravity.CENTER);r.addView(pctV,lp(d(58),d(54)));Button ed=btn("Edit",BLUE);r.addView(ed,lp(d(62),d(44)));Button de=btn("Delete",RED);r.addView(de,lp(d(76),d(44)));ed.setOnClickListener(v->dialog(ix,refresh[0]));de.setOnClickListener(v->{ps.remove(ix);save();refresh[0].run();});list.addView(r,lp(-1,d(66)));gapIn(list,7);}LinearLayout total=card();total.addView(b("Total Percentage",14,MUTED),wt(d(48),1));TextView val=b(f(pct())+"%",17,pct()>100?RED:TEAL);val.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);total.addView(val,wt(d(48),1));list.addView(total,lp(-1,d(50)));};refresh[0]=render;add.setOnClickListener(v->dialog(-1,refresh[0]));render.run();}
 void dialog(int i,Runnable refresh){Product p=i>=0?ps.get(i):new Product("",0,0);LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(d(16),0,d(16),0);EditText name=e("Product Name",p.n),pctE=e("Sales Percentage (%)",f(p.p)),price=e("Carton Price",f(p.c));form.addView(name,lp(-1,d(50)));gapIn(form,9);form.addView(pctE,lp(-1,d(50)));gapIn(form,9);form.addView(price,lp(-1,d(50)));AlertDialog dlg=new AlertDialog.Builder(this).setTitle(i<0?"Add Product":"Edit Product").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();dlg.setOnShowListener(v->dlg.getButton(-1).setOnClickListener(x->{String nm=name.getText().toString().trim();if(nm.isEmpty()){name.setError("Enter product name");return;}if(i<0)ps.add(new Product(nm,num(pctE.getText().toString()),num(price.getText().toString())));else{ps.get(i).n=nm;ps.get(i).p=num(pctE.getText().toString());ps.get(i).c=num(price.getText().toString());}save();dlg.dismiss();refresh.run();}));dlg.show();}
 void hide(){View v=getCurrentFocus();if(v!=null){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);v.clearFocus();}}
}
