package com.example.salestracker;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    final int NAVY=Color.rgb(13,43,78), TEAL=Color.rgb(0,166,132), BLUE=Color.rgb(37,116,226), PURPLE=Color.rgb(112,76,190), RED=Color.rgb(205,68,68), BG=Color.rgb(247,249,252), TEXT=Color.rgb(29,43,61), MUTED=Color.rgb(105,117,132), BORDER=Color.rgb(220,228,238);
    LinearLayout content; String page="home"; SharedPreferences prefs; ArrayList<Product> products=new ArrayList<>();
    static class Product {String name;double pct,price;Product(String n,double p,double c){name=n;pct=p;price=c;}}
    int d(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}
    LinearLayout.LayoutParams wt(int h,float w){return new LinearLayout.LayoutParams(0,h,w);}
    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;}
    GradientDrawable outline(){GradientDrawable g=bg(Color.WHITE,12);g.setStroke(d(1),BORDER);return g;}
    TextView txt(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    TextView btxt(String s,float z,int c){TextView v=txt(s,z,c);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(15);e.setTextColor(TEXT);e.setSingleLine(true);e.setPadding(d(12),0,d(12),0);e.setBackground(outline());return e;}
    EditText small(String value){EditText e=input("",value);e.setTextSize(13);e.setGravity(Gravity.CENTER);e.setPadding(d(3),0,d(3),0);return e;}
    Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setMinHeight(0);b.setMinWidth(0);b.setPadding(d(8),0,d(8),0);b.setBackground(bg(c,13));return b;}
    void add(View v){content.addView(v,lp(-1,-2));}
    void space(int h){Space s=new Space(this);content.addView(s,lp(-1,d(h)));}
    void gap(LinearLayout l,int h){Space s=new Space(this);l.addView(s,lp(-1,d(h)));}

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);prefs=getSharedPreferences("sales_tracker",0);load();home();}
    @Override public void onBackPressed(){if(!page.equals("home"))home();else super.onBackPressed();}
    void load(){products.clear();String raw=prefs.getString("products","");if(raw.length()==0){defaults();return;}for(String s:raw.split("\\|")){String[] x=s.split("~",-1);if(x.length==3)try{products.add(new Product(x[0],Double.parseDouble(x[1]),Double.parseDouble(x[2])));}catch(Exception ignored){}}if(products.isEmpty()){prefs.edit().remove("products").apply();defaults();}}
    void defaults(){products.add(new Product("Korean 40gm Chain",31,2250));products.add(new Product("4pcs",9,1728));products.add(new Product("8pcs CP",8,1692));products.add(new Product("14pcs",12,2120));products.add(new Product("Low Fat",5,1020));products.add(new Product("Ramen 5pcs",14,2400));products.add(new Product("Nata",3,550));products.add(new Product("Ice Lolly",5,989));products.add(new Product("Jhal Boroi",6,1407));products.add(new Product("Jelly",7,1350));}
    void save(){StringBuilder s=new StringBuilder();for(Product p:products)s.append(p.name.replace("~"," ")).append("~").append(p.pct).append("~").append(p.price).append("|");prefs.edit().putString("products",s.toString()).apply();}
    double n(String s){try{return Double.parseDouble(s.replace(",","").replace("৳","").trim());}catch(Exception e){return 0;}}
    String f(double x){return Math.abs(x-Math.round(x))<.001?""+Math.round(x):String.format(Locale.US,"%.2f",x);}
    String money(double x){return "৳ "+String.format(Locale.US,"%,.0f",x);}
    double totalPct(){double x=0;for(Product p:products)x+=p.pct;return x;}
    long carton(double a,double p){return p>0?(long)Math.ceil(a/p):0;}

    void base(String title,String id){page=id;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(d(8),0,d(14),0);bar.setBackgroundColor(NAVY);root.addView(bar,lp(-1,d(56)));
        if(!id.equals("home")){TextView back=btxt("‹",32,Color.WHITE);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->home());bar.addView(back,lp(d(42),d(56)));}
        TextView titleV=btxt(title,20,Color.WHITE);titleV.setPadding(d(6),0,0,0);bar.addView(titleV,wt(d(56),1));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(d(14),d(14),d(14),d(24));scroll.addView(content,lp(-1,-2));root.addView(scroll,lp(-1,0));((LinearLayout.LayoutParams)scroll.getLayoutParams()).weight=1;setContentView(root);}

    LinearLayout card(int radius){LinearLayout x=new LinearLayout(this);x.setBackground(bg(Color.WHITE,radius));x.setPadding(d(16),d(12),d(16),d(12));return x;}
    void home(){base("Sales Tracker","home");
        LinearLayout hero=card(18);hero.setOrientation(LinearLayout.VERTICAL);hero.addView(btxt("Welcome Back!",25,NAVY),lp(-1,d(38)));hero.addView(txt("Plan smart. Sell better.",15,MUTED),lp(-1,d(28)));add(hero);space(12);
        homeCard("🎯","Sales Planning Maker","Set a target and create product-wise planning.",TEAL,()->planning());space(10);
        homeCard("◔","Product Wise Sales","Enter sales → estimate → edit → final result.",BLUE,()->wise());space(10);
        homeCard("⚙","Product Setup","Manage product name, sales % and carton price.",PURPLE,()->setup());space(14);
        LinearLayout stats=card(16);stats.setGravity(Gravity.CENTER);TextView a=btxt("Products\n"+products.size(),14,TEXT);a.setGravity(Gravity.CENTER);stats.addView(a,wt(d(56),1));TextView c=btxt("Total %\n"+f(totalPct())+"%",14,TEAL);c.setGravity(Gravity.CENTER);stats.addView(c,wt(d(56),1));add(stats);
    }
    void homeCard(String icon,String title,String sub,int color,View.OnClickListener click){LinearLayout x=card(18);x.setOrientation(LinearLayout.VERTICAL);x.setOnClickListener(click);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView i=txt(icon,24,color);i.setGravity(Gravity.CENTER);h.addView(i,lp(d(42),d(42)));TextView t=btxt(title,19,color);t.setPadding(d(8),0,0,0);h.addView(t,wt(d(42),1));x.addView(h,lp(-1,d(44)));TextView s=txt(sub,14,MUTED);s.setPadding(d(50),0,0,0);x.addView(s,lp(-1,d(30)));add(x);}

    void planning(){base("Sales Planning Maker","planning");add(btxt("Create your target plan",19,NAVY));space(4);add(btxt("Total Target",14,TEXT));EditText target=input("Enter target amount","500000");add(target);space(10);Button calc=button("Calculate Planning",TEAL);add(calc);space(12);
        LinearLayout table=card(18);table.setOrientation(LinearLayout.VERTICAL);add(table);
        Runnable render=()->{table.removeAllViews();LinearLayout h=new LinearLayout(this);h.addView(btxt("PRODUCT",11,NAVY),wt(d(34),1));h.addView(btxt("%",11,NAVY),lp(d(55),d(34)));h.addView(btxt("AMOUNT",11,NAVY),lp(d(92),d(34)));h.addView(btxt("CARTON",11,NAVY),lp(d(62),d(34)));table.addView(h,lp(-1,d(34)));double targetValue=n(target.getText().toString()),sum=0;long cs=0;for(Product p:products){double amount=targetValue*p.pct/100;long c=carton(amount,p.price);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView name=txt(p.name,13,TEXT);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(name,wt(d(50),1));r.addView(small(f(p.pct)),lp(d(55),d(46)));r.addView(small(String.format(Locale.US,"%.0f",amount)),lp(d(92),d(46)));r.addView(small(""+c),lp(d(62),d(46)));table.addView(r,lp(-1,d(54)));sum+=amount;cs+=c;}table.addView(btxt("TOTAL     "+f(totalPct())+"%     "+money(sum)+"     "+cs+" cartons",13,TEAL),lp(-1,d(42)));};calc.setOnClickListener(v->{hide();render.run();});render.run();}

    void wise(){base("Product Wise Sales","wise");add(btxt("Estimate product-wise sales",19,NAVY));space(4);add(btxt("Total Sales",14,TEXT));EditText sales=input("Enter total sales","15200");add(sales);space(10);Button get=button("Get Estimated Result",BLUE);add(get);space(12);
        LinearLayout table=card(18);table.setOrientation(LinearLayout.VERTICAL);add(table);
        Runnable render=()->{table.removeAllViews();table.addView(btxt("Estimated values — edit % / amount / carton",13,NAVY),lp(-1,d(34)));LinearLayout h=new LinearLayout(this);h.addView(btxt("PRODUCT",11,NAVY),wt(d(34),1));h.addView(btxt("%",11,NAVY),lp(d(55),d(34)));h.addView(btxt("AMOUNT",11,NAVY),lp(d(92),d(34)));h.addView(btxt("CARTON",11,NAVY),lp(d(62),d(34)));table.addView(h,lp(-1,d(34)));double total=n(sales.getText().toString());for(Product p:products){double amount=total*p.pct/100;long c=carton(amount,p.price);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView name=txt(p.name,13,TEXT);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(name,wt(d(50),1));r.addView(small(f(p.pct)),lp(d(55),d(46)));r.addView(small(String.format(Locale.US,"%.0f",amount)),lp(d(92),d(46)));r.addView(small(""+c),lp(d(62),d(46)));table.addView(r,lp(-1,d(54)));}gap(table,10);Button fin=button("✓  Final Result",TEAL);table.addView(fin,lp(-1,d(50)));fin.setOnClickListener(v->{hide();finalPage(total,table);});};get.setOnClickListener(v->{hide();render.run();});render.run();}

    void finalPage(double inputTotal,LinearLayout table){base("Final Result","final");double ps=0,as=0;long cs=0;ArrayList<String[]> rows=new ArrayList<>();for(int i=2;i<table.getChildCount();i++){View v=table.getChildAt(i);if(!(v instanceof LinearLayout))continue;LinearLayout r=(LinearLayout)v;if(r.getChildCount()<4)continue;try{String name=((TextView)r.getChildAt(0)).getText().toString();double p=n(((EditText)r.getChildAt(1)).getText().toString());double a=n(((EditText)r.getChildAt(2)).getText().toString());long c=Math.round(n(((EditText)r.getChildAt(3)).getText().toString()));ps+=p;as+=a;cs+=c;rows.add(new String[]{name,f(p)+"%",money(a),""+c});}catch(Exception ignored){}}add(btxt("✓ Final Product-Wise Sales",21,TEAL));space(8);LinearLayout sum=card(18);sum.setOrientation(LinearLayout.VERTICAL);summary(sum,"Input Sales",money(inputTotal));summary(sum,"Final Amount",money(as));summary(sum,"Total Carton",""+cs);summary(sum,"Total Percentage",f(ps)+"%");add(sum);space(12);LinearLayout out=card(18);out.setOrientation(LinearLayout.VERTICAL);LinearLayout h=new LinearLayout(this);cell(h,"PRODUCT",1,TEXT,true);cell(h,"%",.55f,TEXT,true);cell(h,"AMOUNT",1.1f,TEXT,true);cell(h,"CARTON",.75f,TEXT,true);out.addView(h,lp(-1,d(38)));for(String[] row:rows){LinearLayout r=new LinearLayout(this);cell(r,row[0],1,TEXT,false);cell(r,row[1],.55f,TEXT,false);cell(r,row[2],1.1f,TEXT,false);cell(r,row[3],.75f,TEXT,false);out.addView(r,lp(-1,d(44)));}add(out);space(14);Button home=button("Back to Home",TEAL);add(home);home.setOnClickListener(v->home());}
    void summary(LinearLayout p,String a,String b){LinearLayout r=new LinearLayout(this);r.addView(txt(a,14,MUTED),wt(d(34),1));TextView x=btxt(b,15,NAVY);x.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.addView(x,wt(d(34),1));p.addView(r,lp(-1,d(34)));}
    void cell(LinearLayout r,String s,float w,int c,boolean bold){TextView v=bold?btxt(s,11,c):txt(s,11,c);v.setSingleLine(true);v.setEllipsize(android.text.TextUtils.TruncateAt.END);v.setPadding(d(3),0,d(3),0);r.addView(v,wt(d(44),w));}

    void setup(){base("Product Setup","setup");add(btxt("Manage your products",19,NAVY));add(txt("Name • Sales % • Carton price",14,MUTED));space(10);Button addButton=button("＋  Add Product",TEAL);add(addButton);space(12);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);add(list);final Runnable[] refresh={null};Runnable render=()->{list.removeAllViews();for(int i=0;i<products.size();i++){final int ix=i;Product p=products.get(i);LinearLayout r=card(14);r.setGravity(Gravity.CENTER_VERTICAL);TextView name=btxt(p.name,14,NAVY);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(name,wt(d(54),1));TextView pct=btxt(f(p.pct)+"%",14,TEAL);pct.setGravity(Gravity.CENTER);r.addView(pct,lp(d(58),d(54)));Button edit=button("Edit",BLUE);r.addView(edit,lp(d(62),d(44)));Button del=button("Delete",RED);r.addView(del,lp(d(76),d(44)));edit.setOnClickListener(v->dialog(ix,refresh[0]));del.setOnClickListener(v->{products.remove(ix);save();refresh[0].run();});list.addView(r,lp(-1,d(66)));gap(list,7);}LinearLayout total=card(14);total.addView(btxt("Total Percentage",14,MUTED),wt(d(48),1));TextView val=btxt(f(totalPct())+"%",17,totalPct()>100?RED:TEAL);val.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);total.addView(val,wt(d(48),1));list.addView(total,lp(-1,d(50)));};refresh[0]=render;addButton.setOnClickListener(v->dialog(-1,refresh[0]));render.run();}
    void dialog(int index,Runnable refresh){Product p=index>=0?products.get(index):new Product("",0,0);LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(d(16),0,d(16),0);EditText name=input("Product Name",p.name),pct=input("Sales Percentage (%)",f(p.pct)),price=input("Carton Price",f(p.price));form.addView(name,lp(-1,d(50)));gap(form,9);form.addView(pct,lp(-1,d(50)));gap(form,9);form.addView(price,lp(-1,d(50)));AlertDialog dlg=new AlertDialog.Builder(this).setTitle(index<0?"Add Product":"Edit Product").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();dlg.setOnShowListener(v->dlg.getButton(-1).setOnClickListener(x->{String nm=name.getText().toString().trim();if(nm.isEmpty()){name.setError("Enter product name");return;}double pc=n(pct.getText().toString()),pr=n(price.getText().toString());if(index<0)products.add(new Product(nm,pc,pr));else{products.get(index).name=nm;products.get(index).pct=pc;products.get(index).price=pr;}save();dlg.dismiss();refresh.run();}));dlg.show();}
    void hide(){View v=getCurrentFocus();if(v!=null){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);v.clearFocus();}}
}
