plugins { id 'com.android.application' }

android {
    namespace 'com.example.salestracker'
    compileSdk 35
    defaultConfig {
        applicationId 'com.example.salestracker'
        minSdk 23
        targetSdk 34
        versionCode project.findProperty('VERSION_CODE')?.toString()?.toInteger() ?: 3
        versionName project.findProperty('VERSION_NAME')?.toString() ?: '1.2'
    }
}
